"""
Django settings for supernote_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path: Path) -> None:
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            continue

        key, value = line.split("=", 1)
        key = key.strip()
        if not key:
            continue

        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'\"', "'"}:
            value = value[1:-1]

        os.environ.setdefault(key, value)


ENV_FILE = Path(os.environ.get("SUPERNOTE_ENV_FILE", BASE_DIR / ".env"))
_load_env_file(ENV_FILE)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-gpkq8v=uohvn$s-^=d%x%90g16ucktia49hg$os-x=(6&hi=0+",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").strip().lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "rockpigeon,localhost,127.0.0.1").split(",")
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'django_htmx',
    'files',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'supernote_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'files.context_processors.sync_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'supernote_project.wsgi.application'

TAILWIND_APP_NAME = 'theme'

INTERNAL_IPS = [
    "127.0.0.1",
]

# SuperNote Configuration
DATA_DIR = Path(os.environ.get("SUPERNOTE_DATA_DIR", BASE_DIR))
SUPERNOTE_SOURCE = Path(os.environ.get("SUPERNOTE_SOURCE", DATA_DIR / "Supernote"))
SUPERNOTE_REMOTE = os.environ.get("SUPERNOTE_REMOTE", "SuperNote:Supernote")
SUPERNOTE_SYNC_LOCK_FILE = Path(
    os.environ.get("SUPERNOTE_SYNC_LOCK_FILE", DATA_DIR / ".sync" / "supernote.lock")
)
SUPERNOTE_SYNC_INTERVAL_MINUTES = 10
ARCHIVE_DIR = Path(os.environ.get("SUPERNOTE_ARCHIVE_DIR", DATA_DIR / "ARCHIVE"))
PROCESSED_MD_DIR = Path(os.environ.get("SUPERNOTE_PROCESSED_DIR", DATA_DIR / "PROCESSED_NOTES"))
SUPERNOTE_TOOL_COMMAND = os.environ.get("SUPERNOTE_TOOL_COMMAND", "supernote-tool")


def _env_bool(name: str, default: bool = True) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


SUPERNOTE_SYNC_ENABLED = _env_bool("SUPERNOTE_SYNC_ENABLED", True)
ZOTERO_ENABLED = _env_bool("ZOTERO_ENABLED", True)
KOOFR_ENABLED = _env_bool("KOOFR_ENABLED", True)
AI_PROCESSING_ENABLED = _env_bool("AI_PROCESSING_ENABLED", True)
PERIODICALS_ENABLED = _env_bool("PERIODICALS_ENABLED", True)

# Zotero Configuration
ZOTERO_API_BASE = os.environ.get("ZOTERO_API_BASE", "https://api.zotero.org")
ZOTERO_API_KEY = os.environ.get("ZOTERO_API_KEY", "")
ZOTERO_USER_ID = os.environ.get("ZOTERO_USER_ID", "")
ZOTERO_LIBRARY_TYPE = os.environ.get("ZOTERO_LIBRARY_TYPE", "user")
ZOTERO_DEVICE_DIR = SUPERNOTE_SOURCE / "Document" / "ZoteroSync"
ZOTERO_ARCHIVE_DIR = ARCHIVE_DIR / "zotero"
KOOFR_BASE_URL = os.environ.get("KOOFR_BASE_URL", "https://app.koofr.net/dav/Koofr/zotero")
KOOFR_USER_NAME = os.environ.get("KOOFR_USER_NAME", "")
KOOFR_TOKEN = os.environ.get("KOOFR_TOKEN", "")

# Periodicals Configuration
PERIODICAL_DEVICE_DIR = SUPERNOTE_SOURCE / "Document" / "News"
PERIODICAL_ARCHIVE_DIR = ARCHIVE_DIR / "periodicals"
PERIODICAL_RECIPE_DIR = PERIODICAL_ARCHIVE_DIR / "recipes"
CALIBRE_EBOOK_CONVERT = os.environ.get("CALIBRE_EBOOK_CONVERT", "ebook-convert")
PERIODICAL_OUTPUT_FORMAT = os.environ.get("PERIODICAL_OUTPUT_FORMAT", "epub")

# AI Configuration
GOOGLE_GENAI_API_KEY = (
    os.environ.get("GOOGLE_GENAI_API_KEY")
    or os.environ.get("GEMINI_API_KEY")
    or os.environ.get("GOOGLE_API_KEY")
    or ""
)
GOOGLE_GENAI_MODEL = os.environ.get("GOOGLE_GENAI_MODEL", "gemini-3.6-flash")


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': Path(os.environ.get("SUPERNOTE_DATABASE_PATH", DATA_DIR / "db.sqlite3")),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get("SUPERNOTE_STATIC_ROOT", BASE_DIR / "staticfiles"))
