#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
STATE_DIR="${STATE_DIR:-/srv/supernote-app}"
COMPOSE_ENV="${COMPOSE_ENV:-${STATE_DIR}/config/compose.env}"
COMPOSE_FILE="${PROJECT_ROOT}/compose.yaml"

if [[ -f "${COMPOSE_ENV}" ]]; then
    set -a
    # Generated by install.sh and limited to simple KEY=VALUE entries.
    source "${COMPOSE_ENV}"
    set +a
fi

STATE_DIR="${STATE_DIR:-/srv/supernote-app}"
APP_PORT="${APP_PORT:-8000}"
BIND_ADDRESS="${BIND_ADDRESS:-0.0.0.0}"

compose() {
    docker compose --env-file "${COMPOSE_ENV}" -f "${COMPOSE_FILE}" "$@"
}

require_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        echo "Run this command with sudo." >&2
        exit 1
    fi
}

wait_for_health() {
    local attempts="${1:-60}"
    local url="http://127.0.0.1:${APP_PORT}/"
    for ((i = 1; i <= attempts; i++)); do
        if curl --fail --silent --show-error --max-time 5 "${url}" >/dev/null 2>&1; then
            return 0
        fi
        sleep 5
    done
    echo "Health check failed: ${url}" >&2
    return 1
}
