# Generated by Django 6.0.6 on 2026-06-17 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size', models.BigIntegerField(default=0)),
                ('last_modified', models.DateTimeField()),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('is_directory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.filenode')),
            ],
            options={
                'ordering': ['is_directory', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_path', models.CharField(max_length=1024)),
                ('version_hash', models.CharField(max_length=64)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('file_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='files.filenode')),
            ],
        ),
    ]
