# Generated by Django 6.0.6 on 2026-06-17 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markdown_content', models.TextField()),
                ('last_processed_hash', models.CharField(max_length=64)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('file_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_note', to='files.filenode')),
            ],
        ),
        migrations.CreateModel(
            name='NoteAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=1024)),
                ('asset_type', models.CharField(max_length=50)),
                ('processed_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='files.processednote')),
            ],
        ),
    ]
