# Generated by Django 6.0.6 on 2026-06-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_processednote_noteasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenode',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
