# Generated by Django 6.0.6 on 2026-07-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_zotero_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoteroitem',
            name='attachment_link_mode',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='zoteroitem',
            name='attachment_path',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='zoteroitem',
            name='attachment_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='zoteroitem',
            name='date_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoteroitem',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zoteroitem',
            name='last_transfer_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='zoteroitem',
            name='last_transfer_status',
            field=models.CharField(blank=True, default='idle', max_length=32),
        ),
    ]
