# Generated by Django 6.0.6 on 2026-07-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_zoteroitem_attachment_link_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoteroitem',
            name='is_recycled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zoteroitem',
            name='recycled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
