# Generated by Django 6.0.6 on 2026-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_zoteroitem_is_recycled_zoteroitem_recycled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filenode',
            name='is_recycled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filenode',
            name='recycle_source_is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filenode',
            name='recycled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
