# Generated by Django 6.0.6 on 2026-07-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_filenode_is_recycled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicalRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('recipe_url', models.URLField(blank=True, default='', max_length=1024)),
                ('recipe_path', models.CharField(blank=True, default='', max_length=1024)),
                ('enabled', models.BooleanField(default=False)),
                ('renew_interval_days', models.PositiveIntegerField(default=7)),
                ('retention_days', models.PositiveIntegerField(default=14)),
                ('username_env', models.CharField(blank=True, default='', max_length=128)),
                ('password_env', models.CharField(blank=True, default='', max_length=128)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='idle', max_length=32)),
                ('last_message', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('output_format', models.CharField(default='epub', max_length=16)),
                ('archive_path', models.CharField(max_length=1024)),
                ('debug_path', models.CharField(blank=True, default='', max_length=1024)),
                ('device_path', models.CharField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(default='ready', max_length=32)),
                ('status_message', models.TextField(blank=True, default='')),
                ('is_on_device', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='files.periodicalrecipe')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
